setGeneric("arrayType",     function(object) standardGeneric("arrayType"))
setGeneric("arrayType<-",   function(object, value) standardGeneric("arrayType<-"))
setGeneric("arrayID",       function(object) standardGeneric("arrayID"))
setGeneric("arrayID<-",     function(object, value) standardGeneric("arrayID<-"))
setGeneric("plotQC",        function(object, type) standardGeneric("plotQC"))
setGeneric("reportSamplePanelQC", function(object, by=10, legend=TRUE, ...) standardGeneric("reportSamplePanelQC"))
#setGeneric("reporterInfo",  function(object) standardGeneric("reporterInfo"))
#setGeneric("reporterInfo<-",function(object, value) standardGeneric("reporterInfo<-"))